package otp

import "context"

// Provider defines the interface for sending and verifying OTP codes.
// Implementations:
//   - MockProvider (dev/test): logs the code instead of sending SMS
//   - HTTPProvider (production): calls a real SMS gateway (Clickatell, Twilio, etc.)
//
// The OTP flow:
//  1. Client calls POST /api/otp/send with a phone number
//  2. Provider.Send generates a 6-digit code, stores it (via the repository),
//     and delivers it to the customer via SMS (or logs it in mock mode)
//  3. Client calls POST /api/otp/verify with the phone number + code
//  4. Provider.Verify checks the code against the stored value
//
// The Provider is responsible ONLY for delivery (SMS sending). Code generation,
// storage, rate-limiting, and verification are handled by the OTP service
// (internal/service/otp_service.go) which uses a repository for persistence.
//
// This separation allows swapping SMS providers without touching the OTP logic.
type Provider interface {
	// Send delivers the given OTP code to the given phone number via SMS.
	// The code is generated by the caller (OTP service) — the provider just
	// sends it. Returns an error if the SMS gateway is unreachable.
	Send(ctx context.Context, phone, code string) error

	// Name returns a human-readable identifier for the provider ("mock",
	// "clickatell", "twilio"). Used for logging and metrics.
	Name() string
}
